//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalizaciones
    {
        public int Id_penalizacion { get; set; }
        public Nullable<int> Id_usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> Duracion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
