//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Id_reserva { get; set; }
        public int Id_usuario { get; set; }
        public int Id_hora { get; set; }
    
        public virtual Horas Horas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
